datasource:
  id: a67465ef-c0ad-49a9-8fca-cfd3a931078f
  name: Pima Indians Diabetes Dataset
  source: zenml.core.datasources.csv_datasource.CSVDatasource@zenml_0.1.2
environment:
  artifact_store: /home/user/source/zenml/.zenml/local_store
  backends:
    orchestrator:
      args: {}
      type: local
    processing:
      args: {}
      type: local
    training:
      args: {}
      type: local
  enable_cache: true
  metadata:
    args:
      uri: /home/user/source/zenml/.zenml/local_store/metadata.db
    type: sqlite
  pipeline_name: training_Quickstart_ffc2533a-1ce3-48a6-824e-1fe5ebd8a4d1
steps:
  data:
    args:
      path: gs://zenml_quickstart/diabetes.csv
      schema: null
    source: zenml.core.steps.data.csv_data_step.CSVDataStep@zenml_0.1.2
  evaluation:
    args:
      metrics:
        has_diabetes:
        - binary_crossentropy
        - binary_accuracy
      slices:
      - - has_diabetes
    source: zenml.core.steps.evaluator.tfma_evaluator.TFMAEvaluator@zenml_0.1.2
  preprocessing:
    args:
      features:
      - times_pregnant
      - pgc
      - dbp
      - tst
      - insulin
      - bmi
      - pedigree
      - age
      labels:
      - has_diabetes
      overwrite:
        has_diabetes:
          transform:
          - method: no_transform
            parameters: {}
    source: zenml.core.steps.preprocesser.standard_preprocesser.standard_preprocesser.StandardPreprocesser@zenml_0.1.2
  split:
    args:
      split_map:
        eval: 0.3
        train: 0.7
    source: zenml.core.steps.split.random_split.RandomSplit@zenml_0.1.2
  training:
    args:
      batch_size: 8
      dropout_chance: 0.2
      epochs: 20
      hidden_activation: relu
      hidden_layers: null
      last_activation: sigmoid
      loss: binary_crossentropy
      lr: 0.001
      metrics:
      - accuracy
      output_units: 1
    source: zenml.core.steps.trainer.feedforward_trainer.FeedForwardTrainer@zenml_0.1.2
version: '1'
